api:
  openai:
    api_key: "your-openai-api-key"
    model: "gpt-4"
    max_tokens: 2000
    temperature: 0.7

sonic:
  rpc_url: "https://rpc.blaze.soniclabs.com"
  chain_id: 57054
  private_key: "your-private-key"
  contract_address: "your-contract-address"

zerepy:
  update_interval: 60
  max_slippage: 0.5
  min_liquidity: 1000
  token_address: "your-token-address"
  trading:
    min_amount: 0.1
    max_amount: 1.0
    cooldown_minutes: 5

monitoring:
  telegram_bot_token: "your-telegram-bot-token"
  discord_webhook: "your-discord-webhook"
  log_level: "INFO"
